[package]
name = "ado-autorust"
version = "0.1.0"
authors = ["John Batty <johnbatty@microsoft.com"]
edition = "2021"
publish = false

[dependencies]
autorust_codegen = { path = "../codegen" }
clap = { version = "4", features = ["derive"] }
camino = "1"

[lints]
workspace = true
